export const BLOCKCHAIN__SET_LOADING = '[BLOCKCHAIN] SET_LOADING';
export const BLOCKCHAIN__SET_CONTRACT = '[BLOCKCHAIN] SET_CONTRACT';
export const BLOCKCHAIN__SET_PROVIDER = '[BLOCKCHAIN] SET_PROVIDER';
export const BLOCKCHAIN__FETCH = '[BLOCKCHAIN] FETCH';
export const BLOCKCHAIN__SET_ACCOUNT = '[BLOCKCHAIN] SET_ACCOUNT';
export const BLOCKCHAIN__DISCONNECT = '[BLOCKCHAIN] DISCONNECT';
export const BLOCKCHAIN__SET_IS_CONNECTED = '[BLOCKCHAIN] SET_IS_CONNECTED'
export const BLOCKCHAIN__SPEND_TOKENS = '[BLOCKCHAIN] SPEND_TOKENS';
export const BLOCKCHAIN__SET_TRANSACTION_LOADING = '[BLOCKCHAIN] SET_TRANSACTION_LOADING';
export const BLOCKCHAIN__SET_TRANSACTION_STATUS = '[BLOCKCHAIN] SET_TRANSACTION_STATUS';

export const CONTRACT_INFO__SET_BALANCE = '[CONTRACT_INFO] SET_BALANCE';
export const CONTRACT_INFO__SET_LOADING = '[CONTRACT_INFO] SET_LOADING';
export const CONTRACT_INFO__SET_OWNER = '[CONTRACT_INFO] SET_OWNER';
export const CONTRACT_INFO__FETCH = '[CONTRACT_INFO] FETCH';

export const DATABASE__SET_LOADING = '[DATABASE] SET_LOADING';
export const DATABASE__FETCH_TRANSACTIONS = '[DATABASE] FETCH_TRANSACTIONS';

export const TRANSACTIONS__SET_LOADING = '[TRANSACTIONS] SET_LOADING';
export const TRANSACTIONS__SET = '[TRANSACTIONS] SET';
export const TRANSACTIONS__FETCH = '[TRANSCTIONS] FETCH';
export const TRANSACTIONS_POST_NEW_TRANSACTION = '[TRANSACTIONS] POST_NEW_TRANSACTION';

export const MARKET_PRODUCTS__SET_LOADING = '[MARKET_PLACE] SET_LOADING';
export const MARKET_PRODUCTS__SET = '[MARKET_PLACE] SET';
export const MARKET_PRODUCTS__DELETE = '[MARKET_PLACE] DELETE';
export const MARKET_PRODUCTS__FETCH = '[MARKET_PLACE] FETCH';
export const MARKET_PRODUCTS__ADD_NEW_COLLECTION = '[MARKET_PLACE] ADD NEW COLLECTION';
export const MARKET_PRODUCTS__SET_LATEST_ITEM = '[MARKET_PLACE] SET LATEST ITEM'; 
export const MARKET_PLACE__GET_LATEST_ITEM = '[MARKET_PLACE] GET LATEST ITEM';
export const MARKET_PRODUCTS__SET_SELECTED = '[MARKET_PLACE] SET SELECTED';
export const MARKET_PRODUCTS__SET_SHOW_MODAL = '[MARKET_PLACE] SET SHOW MODAL';
export const MARKET_PLACE__SET_HOW_MUCH = '[MARKET_PLACE] SET HOW MUCH';
export const MARKET_PRODUCTS__UPDATE_BID_ITEM = '[MARKET_PLACE] UPDATE BID ITEM';
export const MARKET_PRODUCTS__SET_DISCORD_NAME = '[MARKET_PLACE] SET_DISCORD_NAME';